### ISSUE TITLE
Not compatible with Ulauncher v4.4.0.r1

### ISSUE THREAD

**Issue by MaggiWuerze** [ralcaidev/ulauncher-extension-list#1]
Unexpected API error. VersionIncompatibilityError: Extension "com.github.ralcaidev.ulauncher-extension-list" is not compatible with Ulauncher v4.4.0.r1

**Comment by julianfrancodev** [comment]
Same iusse...

**Comment by lgg** [comment]
Check this fork: https://github.com/ulauncher-extensions/ulauncher-extension-list

It worked for me on v5.14.3

**Comment by ralcaidev** [comment]
Sorry, I've been out for a while... it's fixed.

**Comment by MaggiWuerze** [comment]
Just in time for me ditching windows on my main machine. Thanks
