### ISSUE TITLE
Stuck on Loading...

### ISSUE THREAD

**Issue by whiteshadow713** [ralcaidev/ulauncher-extension-list#2]
The extension just constantly says "Loading... Alt+1" no matter how long I let it hang there.  Any way to fix?
![screensnip1](https://user-images.githubusercontent.com/77185548/104084466-d87ba880-520c-11eb-8612-aac6b2ddaad4.png)

**Comment by fabOnReact** [comment]
I'm on v 5.14.0 still does not work tried upgrading did not work

**Comment by lgg** [comment]
Check this fork: https://github.com/ulauncher-extensions/ulauncher-extension-list

It worked for me on v5.14.3

**Comment by ralcaidev** [comment]
Sorry, I've been out for a while... it's fixed.
